import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import '../styles/theme.css';
import { Toaster } from '@/components/ui/sonner';
import Provider from '@/lib/provider';

export const fontPoppins = Poppins({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: '--font-poppins',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: './favicon.ico',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${fontPoppins.variable} scrollbar-body`}>
				<Provider>{children}</Provider>
				<Toaster
					richColors
					className="font-poppins"
					position="bottom-center"
				/>
			</body>
		</html>
	);
}
